### ISSUE TITLE
Usage of test-library

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/doc-library#6]
As a community member / developer, I want to see the repository tested with some code from the mentioned test-library. (at least markdown and spelling)

**Comment by daniel-schier** [comment]
I will implement this during the ext week. test-library is almost done for initial usage.

**Comment by daniel-schier** [comment]
initial push for test-library is done. Some more love needed to have a proper behaviour.

**Comment by daniel-schier** [comment]
will address this in fb-testing
