### ISSUE TITLE
Shields for default testing / test-library test

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/doc-library#7]
As a user / contributer / developer, I want to be able to see the Build Status / Test Status in a quick way. shields.io should be implemented and link to the standard tests, defined in test-library.

**Comment by Cinux90** [comment]
How about an overview on the website?
It good to have the shields in the README.md of each repository. But for a quick overview any kind of overview page would be awesome :)

**Comment by daniel-schier** [comment]
@Cinux90 I also thought about an integration on the website to see how many PR/Issues/Commits/etc. are present and we should open an issue for this in the while-true-do/website repository for MS 1.0.0.

Would you be so kind?

PS: Please read the new Contribution Guideline beforehand ;)
